
export type AUTH_CALL_BACK_TYPE = (auth : boolean) => void;

export type CAMERA_PHOTO_SIZE = {
	width : number,
	height : number
}
export type xCamreaUOpts = {
	autoOpenCamera : boolean,
	/**
	 * 是否打开闪光灯,对于orientation为back有效.
	 */
	flash : boolean,
	/**
	 * 摄像头朝向,默认是后置
	 * back,front
	 */
	orientation : string,
	/**
	 * 相机的像素宽
	 */
	cameraWidth : number,
	/**
	 * 相机的像素高
	 */
	cameraHeight : number,
	/**
	 * 容器的宽和高
	 */
	width : number,
	/**
	 * 容器的宽和高
	 */
	height : number
}