import App from './App'
// 源码用户
import { xui, xStore } from "@/uni_modules/tmx-ui/index.uts"
import { Tmui4xOptions } from "@/uni_modules/tmx-ui/interface.uts"

xStore.getThemePrimary()
xStore.setDarkModel('light')

import { createSSRApp } from 'vue'
export function createApp() {
  const app = createSSRApp(App)

  app.use(xui,
    {
      config: {
        color: '#E93030'
      }, // 可选，tmui主题配置
      i18nOptions: null // 可选，多语言配置
    } as Tmui4xOptions
  )
 
  return {
    app
  }
}
