export class DownLoadTaskHasMap {
	public static instanceReal : DownLoadTaskHasMap | null = null;
	tasks:Map<string,DownloadTask> = new Map<string,DownloadTask>()
	public static getInstance() : DownLoadTaskHasMap {
		if (DownLoadTaskHasMap.instanceReal == null) {
			DownLoadTaskHasMap.instanceReal = new DownLoadTaskHasMap();
		}
		return DownLoadTaskHasMap.instanceReal;
	}
	create(uid?:string,params?:UTSJSONObject,su:(d:DownloadFileSuccess)=>void,fa:(d:DownloadFileFail )=>void,progressUpdate:(d:OnProgressDownloadResult )=>void):string|null{
		if(uid ==''||uid==null) return null;
		const _this = this;
		let arg = (params ?? {}) as UTSJSONObject
		const url:string = (arg['url'] as string|null)??''
		const header:UTSJSONObject|null = (arg['header'] as UTSJSONObject|null)??null
		const filePath:string|null = (arg['filePath'] as string|null)??null
		const timeout:number = (arg['filePath'] as number|null)??120000
		const task = uni.downloadFile({
			url,
			header:header,
			filePath,
			timeout,
			success(result:DownloadFileSuccess ){
				su(result)
			},
			fail(result){
				fa(result)
			},
			complete(){
				_this.tasks.delete(uid)
			}
		})
		
		task.onProgressUpdate(res=>{
			progressUpdate(res)
			
		})
		
		this.tasks.set(uid,task)
		return uid
	}
}