import { x_ocrDecode } from "x_ocr_s"
import {XOcrOpts,XOcrFail,XOcrResult} from "../interface.uts"
import {XOcrImpl} from "../unierror.uts"
export function xOcrPare(opts:XOcrOpts) {
	if(opts.path==''){
		opts.fail?.(new XOcrImpl(1004))
		opts.complete?.(null)
		return;
	}
	try {
		x_ocrDecode(UTSHarmony.convert2AbsFullPath(opts.path), (texts:string[],textblock:string[])=>{
			if(texts.length==0){
				opts.fail?.(new XOcrImpl(1001))
				opts.complete?.(null)
				return;
			}
			const resultJg:XOcrResult = {
				text:texts,
				textBlock:textblock
			}
			opts.success?.(resultJg)
			opts.complete?.(resultJg)
		})
	} catch (error) {
		console.error("X-OCR Error:",error)
		opts.fail?.(new XOcrImpl(1002))
		opts.complete?.(null)
	}
}
export function localFilePathImageBuilder(pathfile : string,callback:(str:string[],source:string[])=>void,langs:string|null){
	
	x_ocrDecode(UTSHarmony.convert2AbsFullPath(pathfile), callback)
}