import { xWebviewUOpts, uniAppEvaJsTypeCallBackFun, uniAppEvaJsTypeOnUpdate,TmuiSchemaType, uniAppPostmessageType } from '../interface';
import { jsCodeToBody, jsCodeToBodyEn,jsCodeToBodyRepeat } from "../libs/evealJsJscore.uts"
import { WKDownload,WKNavigationResponsePolicy, WKNavigation, WKNavigationAction, WKNavigationDelegate,WKNavigationActionPolicy, WKNavigationResponse, WKScriptMessage, WKScriptMessageHandler, WKUIDelegate, WKUserContentController, WKWebView , WKWebViewConfiguration, WKUserScriptInjectionTime, WKUserScript } from "WebKit";
import { UIApplication, UIDevice, UIView, UIViewController,UIUserInterfaceStyle, UIScrollView } from 'UIKit';
import { NSObject } from 'ObjectiveC';
import { URLRequest , URL , CachePolicy , NSURLRequest,NSError, NSString , Bundle, NSNumber, HTTPURLResponse } from 'Foundation';

import {addConsoloeJs,ConsoleLogHandler,addAddLoadProgressJs,overMessageActions } from "./xlib/jscodebody.uts"
import { Object } from 'RoomPlan';

class XWKuiDelegate implements WKUIDelegate<NSObject> {
	
}
type HtmlContentTypes = {
	mimeType:string,
	contentLenght:number,
	url:string
}
let htmlContentType:HtmlContentTypes = {
	mimeType:"",
	contentLenght:0,
	url:""
}
class xuiWKNavigationDelegate implements WKNavigationDelegate<NSObject> {
	ctx : UIViewController|null = null;
	webview : WKWebView|null = null;
	config : xWebviewUOpts|null = null;
	private webviewProgressChanged = (n : number) => { }
	private webviewLoadCallbackStatus = (type : string,url:string) => { }
	private allowLoadUrl = (url?:string|null):boolean => (true);
	private allowLoadUrlWhite:string[] = []
	private schemas:TmuiSchemaType[] = [];
	private webviewDonwloadChanged = (url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => {}
	constructor(){
		super()
	}
	setBaseOpts(ctx : UIViewController, webview : WKWebView, config : xWebviewUOpts) {
		this.ctx = ctx;
		this.webview = webview;
		this.config = config;
	}
	// 导航开始
	webView(webview:WKWebView,@argumentLabel("didStartProvisionalNavigation") navigation:WKNavigation){
		const url = webview.url?.absoluteString??''
		this.webviewLoadCallbackStatus('start',url)
		this.webviewProgressChanged(Number(webview.estimatedProgress))
	}
	//开始接收页面内容加载。
	webView(webview:WKWebView,@argumentLabel("didCommit") navigation:WKNavigation){
		const url = webview.url?.absoluteString??''
		this.webviewProgressChanged(Number(webview.estimatedProgress))
	}
	webView(webview:WKWebView,@argumentLabel("didFinish") navigation:WKNavigation){
		const url = webview.url?.absoluteString??''
		this.config?.onPageFinish?.(url)
		this.webviewProgressChanged(Number(webview.estimatedProgress))
		this.webviewLoadCallbackStatus('end',url)
	}
	webView(webview:WKWebView,@argumentLabel("didFail") navigation:WKNavigation,@argumentLabel("withError") error:NSError){
		const url = webview.url?.absoluteString??''
		this.config?.onPageError?.(url)
		this.webviewProgressChanged(0)
		this.webviewLoadCallbackStatus('error',url)
	}
	
	@UTSiOS.available("iOS 14.0, *")
	webView(webview:WKWebView,@argumentLabel("decidePolicyFor") navigationResponse: WKNavigationResponse,@argumentLabel("") @escaping decisionHandler:((arg:WKNavigationActionPolicy)=>void)){
		console.log('Content-Disposition',navigationResponse.response.mimeType)
		decisionHandler(WKNavigationActionPolicy.cancel)
	}
	@UTSiOS.available("iOS 14.5, *")
	webView(webview:WKWebView,@argumentLabel("") navigationResponse: WKNavigationResponse,@argumentLabel("didBecome") download:WKDownload){
		
		
		// DispatchQueue.main.async(execute=():void => {
		// 	this.allowLoadUrl(url).then((isAllow:boolean)=>{
		// 		console.log('isAllow',isAllow)
		// 		decisionHandler(isAllow?WKNavigationResponsePolicy.allow:WKNavigationResponsePolicy.cancel)
				
		// 	}).catch(er=>{
		// 		console.log('isAllow error',er)
		// 		decisionHandler(WKNavigationResponsePolicy.cancel)
				
		// 	})
		// })
		
	}
	
	//响应内容后是否允许继续加载。这里可以判断内容类型是否允许 下载。
	webView(webview:WKWebView,@argumentLabel("decidePolicyFor") navigationResponse: WKNavigationResponse,@argumentLabel("") @escaping decisionHandler:((arg:WKNavigationResponsePolicy)=>void)){
		const url = webview.url?.absoluteString??''
		htmlContentType.url = url
		htmlContentType.mimeType = navigationResponse.response.mimeType
		htmlContentType.contentLenght = Number(navigationResponse.response.expectedContentLength)
		const desc = navigationResponse.response.url?.description??''
		// 属性ios私有属性，文档无法查询到
		const response = navigationResponse.response as HTTPURLResponse
		const contentDisposition = (response.allHeaderFields.get('Content-Disposition')??'') as string
		// 通过minetype来检测是否是下载文件。
		if(htmlContentType.mimeType.startsWith('application')){
			DispatchQueue.main.async(execute=():void => {
				this.webviewDonwloadChanged(
				htmlContentType.url,
				contentDisposition,
				desc,
				htmlContentType.mimeType,
				htmlContentType.contentLenght
				)
			})
			decisionHandler(WKNavigationResponsePolicy.cancel)
		}else{
			decisionHandler(WKNavigationResponsePolicy.allow)
		}
	}
	// 请示前判断是否允许请示
	webView(webview:WKWebView,@argumentLabel("decidePolicyFor") navigationAction: WKNavigationAction,@argumentLabel("") @escaping decisionHandler:((arg:WKNavigationActionPolicy)=>void)){
		const uri = navigationAction.request.url
		const url = uri?.absoluteString??''
		// htmlContentType.url = url
		// htmlContentType.mimeType = navigationResponse.response.mimeType
		
		DispatchQueue.main.async(execute=():void => {
			if(url.startsWith('http')||url.startsWith('https')){
				let isAllow = true;
				if(this.allowLoadUrlWhite.length>0){
					isAllow = this.allowLoadUrlWhite.some((el:string):boolean => el.indexOf(url)>-1)
				}
				
				decisionHandler(isAllow?WKNavigationActionPolicy.allow:WKNavigationActionPolicy.cancel)
			}else if(this.schemas.length>0&&uri!=null){
				let index = -1;
				const ss = ['tel:','mailto:','sms:']
				for(let i=0;i<this.schemas.length;i++){
					let item = this.schemas[i]
					if(ss.includes(item.schema)){
						UIApplication.shared.open(uri!)
						break;
					}else if(url.indexOf(item.schema)>-1){
						index = i;
						break;
					}
				}
				
				if(index>-1){
					UIApplication.shared.open(uri!)
				}
				decisionHandler(WKNavigationActionPolicy.cancel)
			}else{
				if(uri!=null){
					UIApplication.shared.open(uri!)
					decisionHandler(WKNavigationActionPolicy.cancel)
				}else{
					decisionHandler(WKNavigationActionPolicy.allow)
				}
			}
			
		})
	}
	
	setWebviewProgressLoad(fn:(n:number)=>void){
		this.webviewProgressChanged = fn;
	}
	// webView(webview:WKWebView,navigationAction: WKNavigationAction,@argumentLabel("didBecome") download: WKDownload){
	// 	navigationAction.
	// }
	setWebviewLoadCallbackStatus(fn:(type : string,url:string) => void){
		this.webviewLoadCallbackStatus = fn;
	}
	//是否允许链接跳转。
	setAllowLoadUrlWhites(s:string[]){
		this.allowLoadUrlWhite = s;
	}
	setSchemass(s:TmuiSchemaType[]){
		this.schemas = s;
	}
	setWebviewDownload(fn:(url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => void ){
		this.webviewDonwloadChanged = fn
	}
}
class WebAppInterface implements WKScriptMessageHandler<NSObject> {
	ctx : UIViewController|null = null;
	webview : WKWebView|null = null;
	config : xWebviewUOpts|null = null;
	private webConfig:UTSJSONObject = {}
	private postMessageCallback = (arg:uniAppPostmessageType)=>{}
	private webviewProgressChanged = (n : number) => { }
	/** 刷新页面 */
	public refresh(){
		DispatchQueue.main.async(execute=():void => {
			this.webview?.reload()
		})
	}
	
	/** 回退页面 */
	public navback(){
		DispatchQueue.main.async(execute=():void => {
			this.webview?.goBack()
		})
	}
	
	/** 前进页面 */
	public forward(){
		DispatchQueue.main.async(execute=():void => {
			this.webview?.goForward()
		})
	}
	
	setBaseOpts(ctx : UIViewController, webview : WKWebView, config : xWebviewUOpts) {
		this.ctx = ctx;
		this.webview = webview;
		this.config = config;
	}
	setConfg(arg?:xWebviewUOpts){
		this.config = arg;
	}
	setwebConfigData(d:UTSJSONObject){
		this.webConfig = d;
	}
	performActionWithCallback(callback : string) {
		let _this = this;
		DispatchQueue.main.async(execute=():void => {
			_this.webview?.evaluateJavaScript(callback,completionHandler = null)
		})
	}
	methodFun(methodName:string,callbackId?:string,params?:UTSJSONObject,callback?:uniAppEvaJsTypeCallBackFun){
		if(callbackId==null) return
		if(methodName == 'app_getWebviewInfo'){
			const bundle = Bundle.main
			const data:UTSJSONObject = {
					packageName:bundle.bundleIdentifier,
					versionName:bundle.infoDictionary!.get('CFBundleShortVersionString'),
					versionCode:bundle.infoDictionary!.get('CFBundleVersion'),
					apiLevel: UIDevice.current.systemVersion,
					env:"uniapp-x ios"
				}
			const d = {
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				type:null,
				data
			}
			callback?.(d)
		}else if(methodName == 'app_openUrl'){
			const hrefUrl:string = params?.getString('url')??''
			let href = new URL(string = hrefUrl)
			if (UTSiOS.available("iOS 16.0, *")) {
				if (UIApplication.shared.canOpenURL(href!)) {
					UIApplication.shared.open(href!, options= new Map(), completionHandler= nil)
				}
			}else{
				if (UIApplication.shared.canOpenURL(href!)) {
					UIApplication.shared.openURL(href!)
				}
			}
			
			callback?.({
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:null
			});
		}else if(methodName == 'app_getUserAgent'){
			let browesr = this.webview!;
			browesr.evaluateJavaScript("navigator.userAgent", completionHandler = (result,_)=>{
				if(typeof result == 'string'){
					const d = {
						callbackId:callbackId!,
						success:true,
						errorMessage:null,
						data:result
					}
					callback?.(d);
				}else{
					const d = {
						callbackId:callbackId!,
						success:true,
						errorMessage:null,
						data:null
					}
					callback?.(d);
				}
			})
		}else if(methodName == 'app_getConfig'){
			const d = {
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:this.webConfig,
				type:null
			}
			callback?.(d);
		}
		
	}
	
	userContentController(userContentController: WKUserContentController,@argumentLabel("didReceive") message: WKScriptMessage){
		const _this=  this;
		const messageName = message.name;
		if(messageName != 'tmuiApp'||message.body == null) return;
		const body = message.body as Map<string,any>
		const action = body.get('action') as string|null
		const data = body.get('data') as string|null
		if(action == 'postMessage'&&data!=null){
			try {
				const message = JSON.parseObject(data)
				if(message == null) return;
				const callbackId = message.getString('callbackId')??null;
				const methodName = message.getString('methodName')??null;
				const params:UTSJSONObject|null = message.getJSON('params')??null;
				if(methodName == null) return;
				
				//分发到本插件宿主环境执行
				if(methodName.indexOf('app_')>-1){
					DispatchQueue.main.async(execute=():void => {
						const onCallbackFun:uniAppEvaJsTypeCallBackFun = (result:UTSJSONObject|null) =>{
							if(callbackId==null) return;
							
							const resultRealData = result==null?"{}":(JSON.stringify(result??{})??"{}")
							_this.performActionWithCallback(`__handleTmuiResponse('${resultRealData}')`)
						}
						_this.methodFun(methodName,callbackId,params,onCallbackFun)
					})
				// 系统分发到uniapp环境执行	
				}else{
					const url = _this.webview?.url?.absoluteString??''
					DispatchQueue.main.async(execute=():void => {
						const onUpdate:uniAppEvaJsTypeOnUpdate = (result:any|null) =>{}
						const onCallbackFun:uniAppEvaJsTypeCallBackFun = (result:UTSJSONObject|null) =>{
							if(callbackId==null) return;
						
							const resultRealData = result==null?"{}":(JSON.stringify(result??{})??"{}")
							_this.performActionWithCallback(`__handleTmuiResponse('${resultRealData}')`)
						}
						_this.config?.uniAppEvaJsIos?.(url,methodName!,callbackId,params,onUpdate,onCallbackFun)
					})
				}
			} catch (error) {
				console.error('TMUIWEBVIEW ERROR',error)
				const message = JSON.parseObject(data)
				if(message == null) return;
				const callbackId = message.getString('callbackId')??null;
				const methodName = message.getString('methodName')??null;
				if(methodName == null) return;
				const result = {
					callbackId:callbackId!,
					success:true,
					errorMessage:'TMUIWEBVIEW ERROR',
					data:null
				}
				_this.performActionWithCallback(`__handleTmuiResponse('${JSON.stringify(result)}')`)
			}
			
		}else if(action == 'clearCache'){
			this.clearCache()
		}else if(action == 'refresh'){
			this.refresh()
		}else if(action == 'navback'){
			this.navback()
		}else if(action == 'forward'){
			this.forward()
		}else if(action == 'toast'){
			uni.showToast({title:data,icon:'none'})
		}else if(action == 'tmuiAppPageLoad'){
			this.webviewProgressChanged(1)
		}else if(action == 'postMessageCustom'){
			DispatchQueue.main.async(execute=():void => {
				this.postMessageCallback({detail:data==null?'':(data)})
			})
		}
		
	}
	clearCache(){
		this.webview?.reloadFromOrigin()
	}
	setWebviewProgressLoad(fn:(n:number)=>void){
		this.webviewProgressChanged = fn;
	}
	setPostMessageFn(fn:(arg:uniAppPostmessageType)=>void){
		this.postMessageCallback = fn;
	}

	
}

export class xWebviewU {
	private $element : UniNativeViewElement;
	private targetView : UIView = new UIView();
	private config : xWebviewUOpts = {
		url:'',
		onPageStart:(url?:string|null)=>{},
		onPageFinish:(url?:string|null)=>{},
		onPageError:(url?:string|null)=>{},
		allowLoadUrl:(url?:string|null)=>true,
		uniActions:(name:string,arg:any|null) => '',
		uniAppEvaJs: (url : string | null, methodName : string, callbackId ?: string, params ?: UTSJSONObject, onUpdate ?: uniAppEvaJsTypeOnUpdate) : Promise<UTSJSONObject|null> => {
			return Promise.resolve(null);
		}
	
	}
	private webview : WKWebView | null = null;
	webChormClient : xuiWKNavigationDelegate|null = null;
	webClient : XWKuiDelegate|null = null;
	private webConfig:UTSJSONObject = {}
	private context : UIViewController | null = null
	public webInterface : WebAppInterface
	public callbackOnUpdate = new Map<string, uniAppEvaJsTypeOnUpdate>()
	private webVarJsCss:string = ''
	private webVarCss:string = ''
	
	// 网页加载进度回调
	private webviewProgressChanged = (n : number) => { }
	private webAllowLoadUrl = (url?:string|null):string => 'boolean';
	
	constructor(element : UniNativeViewElement) {
		this.webInterface = new WebAppInterface()
		this.context = UTSiOS.getCurrentViewController()
		this.$element = element;
		this.$element.bindIOSView(this.targetView);
		
	}
	@UTSJS.keepAlive
	setBaseConfig(opts : xWebviewUOpts) {
		if(this.webview!=null){
			this.targetView.willRemoveSubview(this.webview!)
		}
		this.config = opts;
		// 相关配置。
		const configuration = new WKWebViewConfiguration()
		// 添加日志处理
		configuration.userContentController.addUserScript(addConsoloeJs)
		configuration.userContentController.add(new ConsoleLogHandler(),name = 'tmuiAppLog')
		
		//添加网页加载完成处理函数。
		configuration.userContentController.addUserScript(addAddLoadProgressJs)
		configuration.userContentController.add(new ConsoleLogHandler(),name = 'tmuiAppPageLoad')
		const addMessageActionsJs = new WKUserScript(
			source = overMessageActions(this.webVarJsCss,this.webVarCss),
			injectionTime = WKUserScriptInjectionTime.atDocumentStart,
			forMainFrameOnly = false
		)
		
		// 添加tmuiAPp基本函数处理
		configuration.userContentController.addUserScript(addMessageActionsJs)
		configuration.userContentController.add(this.webInterface,name = 'tmuiApp')
		this.webview  = new WKWebView(frame = this.targetView.bounds, configuration = configuration)
		this.webChormClient =  new xuiWKNavigationDelegate();
		this.webClient = new XWKuiDelegate()
		this.webview!.uiDelegate = this.webClient!
		this.webview!.navigationDelegate = this.webChormClient!
		this.webChormClient!.setBaseOpts(this.context!, this.webview!, this.config)
		
		this.webview!.backgroundColor = UTSiOS.colorWithString('rgba(255,255,255,0)')
		if(UTSiOS.available("iOS 13.0, *")){
			this.webview!.overrideUserInterfaceStyle = UIUserInterfaceStyle.light
		}
		this.webview!.isOpaque = false
		if(UTSiOS.available("iOS 11.0, *")){
			this.webview!.scrollView.contentInsetAdjustmentBehavior = UIScrollView.ContentInsetAdjustmentBehavior.never
		}
		this.webview!.autoresizingMask = [UIView.AutoresizingMask.flexibleWidth, UIView.AutoresizingMask.flexibleHeight]
		
		this.webInterface.setBaseOpts(this.context!, this.webview!, this.config)
		this.webInterface.setwebConfigData(this.webConfig)
		
		this.targetView.addSubview(this.webview!)
		
		this.webInterface.setConfg(this.config)
		this.webChormClient?.setWebviewLoadCallbackStatus((type:string,url:string)=>{
			DispatchQueue.main.async(execute=():void => {
				if(type == 'start'){
					this.config.onPageStart?.(url)
				}else if(type == 'end'){
					this.config.onPageFinish?.(url)
				}else if(type == 'error'){
					this.config.onPageError?.(url)
				}
			})
		})
		
		if (this.config.url != '' && typeof this.config.url =='string') {
			this.loadUrl(this.config.url!)
		}
	}
	destory(){
		this.webview = null;
		// this.webInterface = null
		this.webChormClient = null
		this.webClient = null
		this.callbackOnUpdate.clear()
		UTSiOS.destroyInstance(this)
	}
	evaJs(callback : string) {
		let _this = this;
		DispatchQueue.main.async(execute=():void => {
			_this.webview?.evaluateJavaScript(callback,completionHandler = null)
		})
	}
	
	// 设置用户代理字符串标识。
	setUserAgent(agent ?: string){
		let browesr = this.webview!;
		this.getUserAgent((oldUserAgent:string)=>{
			browesr.customUserAgent = oldUserAgent + (agent??'')
		})
	}
	clearCache(){
		let browesr = this.webview!;
		browesr.reloadFromOrigin()
	}
	//获取用户代理字符串标识。
	getUserAgent(fn:(ag:string)=>void){
		let browesr = this.webview!;
		browesr.evaluateJavaScript("navigator.userAgent", completionHandler = (result,_)=>{
			if(typeof result == 'string'){
				fn(result)
			}else{
				fn('')
			}
		})
	}
	loadUrl(url : string) {
		let browesr = this.webview!;
		const uri = new URLRequest(url = new URL(string = url)!,cachePolicy = NSURLRequest.CachePolicy.useProtocolCachePolicy,timeoutInterval=30)
		browesr.load(uri)
	}
	@UTSJS.keepAlive
	setWebviewLoadUrlProgress(callback : (progress : number) => void) {
		this.webviewProgressChanged = callback
		
		this.webChormClient?.setWebviewProgressLoad((n:number)=>{
			this.webviewProgressChanged(n*100)
		})
		this.webChormClient?.setWebviewProgressLoad((n:number)=>{
			this.webviewProgressChanged(n*100)
		})
	}
	@UTSJS.keepAlive
	setWebviewDownload(callback:(url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => void ){
		this.webChormClient?.setWebviewDownload((url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => {
			this.getUserAgent((ag:string)=>{
				callback(url,ag,contentDisposition,mimeType,contentLength)
			})
		})
	}
	
	@UTSJS.keepAlive
	setPostMessage(fn:(arg:uniAppPostmessageType)=>void){
		this.webInterface.setPostMessageFn((event:uniAppPostmessageType)=>{
			fn(event)
		})
	}

	setwebConfigData(d:UTSJSONObject){
		this.webConfig = d;
		this.webInterface.setwebConfigData(d)
	}
	setSchema(s:TmuiSchemaType[]){
		this.webChormClient?.setSchemass(s)
	}
	setAllowLoadUrlWhites(s:string[]){
		this.webChormClient?.setAllowLoadUrlWhites(s)
	}
	setAppthemeVar(jsCss:string,cssVar:string){
		this.webVarJsCss = jsCss;
		this.webVarCss = cssVar;
	}
	loadUrlmini(url:string){}
	
	
}