import { XOcrOpts, XOcrFail, XOcrResult } from "../interface.uts"
import { XOcrImpl } from "../unierror.uts"
// @ts-ignore
let ocr = window?.paddlejs?.ocr ?? null;
let jsFiles = [
	'/static/tmui4xLibs/lib/ocrLib.js'
];
async function loadScript(url) {
    return new Promise(res=>{
		var script = document.createElement('script');
		script.type = 'text/javascript';
		script.src = url;
		
		// 当脚本加载完成后，执行回调
		script.onload = function() {
		   res()
		};
		
		// 处理旧版浏览器的onreadystatechange事件
		script.onreadystatechange = function() {
		    if (this.readyState === 'loaded' || this.readyState === 'complete') {
		        script.onload();
		    }
		};
		
		// 将脚本添加到head中，开始加载
		document.head.appendChild(script);
	})
}
async function loadScripts(scripts) {
	if(ocr) return Promise.resolve(true)
	await (async function loadNextScript(i) {
		if (i < scripts.length) {
			await loadScript(scripts[i]);
			await loadNextScript(i + 1)
		}
	})(0);

}

export function xOcrPare(opts : XOcrOpts) {
	try {
		// @ts-ignore
		loadScripts(jsFiles)
			.then(() => {
				ocr = paddlejs.ocr
				return ocr.init()
			})
			.then(() => {
				let img = new Image()
				img.src = opts.path
				img.onerror = (error) => {
					console.error("X-OCR Error:", error)
					opts.fail?.(new XOcrImpl(1003))
					opts.complete?.(null)
				}
				img.onload = async function () {
					try {
						const canvas = new OffscreenCanvas(800, 800)
						const res = await ocr.recognize(img, { canvas });
						let texts = res.text
						let bounds = []
						for (let i = 0; i < res.points.length; i++) {
							let item = res.points[i]
							bounds.push({
								x: item[0][0],
								y: item[0][1],
								width: item[1][0] - item[0][0],
								height: item[3][1] + item[0][1]
							})
						}
						const resultJg : XOcrResult = {
							text: texts as string[],
							textBlock: JSON.stringify(bounds)
						}
						opts.success?.(resultJg)
						opts.complete?.(resultJg)
					} catch (error) {
						console.error("X-OCR Error:", error)
						opts.fail?.(new XOcrImpl(1002))
						opts.complete?.(null)
					}
				}
			})
			.catch(error => {
				console.error("X-OCR Error:", error)
				opts.fail?.(new XOcrImpl(1002))
				opts.complete?.(null)
			})

	} catch (error) {
		console.error("X-OCR Error:", error)
		opts.fail?.(new XOcrImpl(1002))
		opts.complete?.(null)
	}
}