import { ChineseTextRecognizerOptions, JapaneseTextRecognizerOptions, TextRecognizer, VisionImage, TextBlock, Text } from "MLKit"
import * as UIKit from "UIKit"
import { UIAlertController, UIAlertAction, UITextField, UIImage } from "UIKit"
import { UTSiOS } from "DCloudUTSFoundation"
import { String } from "Swift"
import { PHPhotoLibrary } from "Photos"
import { CGPoint , CGRect } from 'CoreFoundation';
import {XOcrOpts,XOcrFail,XOcrResult} from "../interface.uts"
import {XOcrImpl} from "../unierror.uts"

export function xOcrPare(opts:XOcrOpts) {
	let local = opts.langs
	if(opts.langs!='zh'&&opts.langs!='ja'){
		opts.fail?.(new XOcrImpl(1004))
		opts.complete?.(null)
		return;
	}
	let chineseOptions = new ChineseTextRecognizerOptions()
	let chineseTextRecognizer = TextRecognizer.textRecognizer(options = chineseOptions)
	if (local == 'ja') {
		chineseTextRecognizer = TextRecognizer.textRecognizer(options = new JapaneseTextRecognizerOptions())
	}

	try {
		let realImgPath = UTSiOS.convert2AbsFullPath(opts.path)
		let img = new UIImage(contentsOfFile = realImgPath);
		if (img != null) {
			let image = new VisionImage(image = img!);
			chineseTextRecognizer.process(image as VisionImage, completion = (TextList, error) => {
				if (error != null || TextList == null) {
					opts.fail?.(new XOcrImpl(1001))
					opts.complete?.(null)
					return;
				}
				let str = [] as string[]
				let sour = [] as string[]
				for (block in TextList!.blocks) {
					let lines = block.lines
					
					if(lines!=null){
						for(line in lines) {
							let elements = line.elements
							if(elements!=null){
								let texts = ''
								for(element in elements) {
								    let elementText = element.text;
									let rect = element.frame as CGRect
									let elementFrame = [rect.origin.x,rect.origin.y,rect.size.width,rect.size.height] as number[]
									sour.push(JSON.stringify({boundingBox:elementFrame,text:elementText})!)
									texts+=elementText
								}
								if(texts!=''){
									str.push(texts)
								}
							}
						    
						}
					}
				}
				const resultJg:XOcrResult = {
					text:str as string[],
					textBlock:sour
				}
				opts.success?.(resultJg)
				opts.complete?.(resultJg)
			})

		}else{
			opts.fail?.(new XOcrImpl(1003))
			opts.complete?.(null)
		}
	} catch (e) {
		console.error("X-OCR Error:",e)
		opts.fail?.(new XOcrImpl(1002))
		opts.complete?.(null)
	}
}