import { xWebviewUOpts, uniAppEvaJsTypeCallBack, uniAppEvaJsTypeOnUpdate,TmuiSchemaType, uniAppPostmessageType, uniAppEvaJsTypeCallBackFun } from '../interface';
import { buildView } from "./builder.ets"
import { BuilderNode, ComponentContent } from "@kit.ArkUI"
import {
	WebviewUCustom,
	H_xWebviewUOpts,
} from "x_webview_u"

// 定义 buildButton 的参数类型
interface NativeXdblurOptions {web:WebviewUCustom}

export class xWebviewU {
	$element : UniNativeViewElement;
	targetView : BuilderNode<[NativeXdblurOptions]> | null = null;
	webInterface:WebviewUCustom
	private params : NativeXdblurOptions
	config:xWebviewUOpts = {
		uniAppEvaJs: (url: string | null, methodName: string, callbackId?: string, params?: UTSJSONObject, onUpdate?: uniAppEvaJsTypeOnUpdate) => Promise.resolve(null)
	}

	constructor(element : UniNativeViewElement) {
		this.webInterface = new WebviewUCustom(UTSHarmony.getCurrentWindow()!.getUIContext());
		const _this = this;
		this.webInterface.setOnInitCallback(()=>{
			_this.webInterface.setHandleWebMessage((str?:string)=>{
				_this.handleWebMessage(str)
			})
			const url = _this.webInterface.config?.url??"";
			if(url!=''){
				_this.webInterface.loadUrl(url)
			}
		})
		
		this.params = {web:this.webInterface}
		this.$element = element
	}
	
	setAppthemeVar(jscss:string,cssvar:string){
		this.webInterface.setAppthemeVar(jscss,cssvar)
	}
	
	methodFun(methodName:string,callbackId?:string,params?:UTSJSONObject,callback?:uniAppEvaJsTypeCallBackFun){
		if(callbackId==null) return
		if(methodName == 'app_getWebviewInfo'){
			const data:string = this.webInterface.getWebInfo()
			const d = {
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				type:null,
				data:JSON.parseObject(data)
			}
			callback?.(d)
		}else if(methodName == 'app_openUrl'){
			const hrefUrl:string = params?.getString('url')??''
			this.webInterface.openURL(hrefUrl)
			callback?.({
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:null
			});
		}else if(methodName == 'app_getUserAgent'){
			const d = {
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:this.webInterface.getUserAgent()
			}
			console.log(methodName,d)
			callback?.(d);
		}else if(methodName == 'app_getConfig'){
			const d = {
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:this.webInterface.webConfig,
				type:null
			}
			callback?.(d);
		}
		
	}
	
	handleWebMessage(str?:string){
		const _this=  this;
		if(!str) return;
		try {
			const message = JSON.parseObject(str)
			if(message == null) return;
			const callbackId = message.getString('callbackId')??null;
			const methodName = message.getString('methodName')??null;
			const params:UTSJSONObject|null = message.getJSON('params')??null;
			if(methodName == null) return;
			const url = this.webInterface.webControl.getUrl()
			if(methodName.startsWith('app_')){
				
				const onCallbackFun:uniAppEvaJsTypeCallBackFun = (result?:UTSJSONObject|null) =>{
					if(callbackId==null) return;
					
					const resultRealData = result==null?"{}":(JSON.stringify(result??{})??"{}")
					_this.webInterface.performActionWithCallback(`__handleTmuiResponse('${resultRealData}')`)
				}
				_this.methodFun(methodName,callbackId,params,onCallbackFun)
				
				return;
			}
		
			const onUpdate:uniAppEvaJsTypeOnUpdate = (result?:Object|null) =>{}
			const onCallbackFun:uniAppEvaJsTypeCallBackFun = (result?:UTSJSONObject|null) =>{
				if(!callbackId) return;
				const resultRealData = !result?"{}":(JSON.stringify(result??{})??"{}")
				_this.webInterface.performActionWithCallback(`__handleTmuiResponse('${resultRealData}')`)
			}
			
			_this.config?.uniAppEvaJsIos?.(url,methodName!,callbackId||"",params||({} as UTSJSONObject),onUpdate,onCallbackFun)
		} catch (error) {
			console.error('TMUIWEBVIEW ERROR',error)
			const message = JSON.parseObject(str)
			if(message == null) return;
			const callbackId = message.getString('callbackId')??null;
			const methodName = message.getString('methodName')??null;
			if(methodName == null) return;
			const result = {
				callbackId:callbackId!,
				success:true,
				errorMessage:'TMUIWEBVIEW ERROR',
				data:null
			}
			_this.webInterface.performActionWithCallback(`__handleTmuiResponse('${JSON.stringify(result)}')`)
		}
	}
	setBaseConfig(opts : xWebviewUOpts) {
		this.config = opts;
		this.webInterface.setBaseConfig(opts as H_xWebviewUOpts)
		this.targetView = this.$element.bindHarmonyWrappedBuilder(wrapBuilder<[NativeXdblurOptions]>(buildView),this.params)
		
		this.$element.bindHarmonyController(this)
	}
	setWebviewLoadUrlProgress(fn:(n:number)=>void){
		this.webInterface.setWebviewLoadUrlProgress(fn)
	}
	setwebConfigData(d:UTSJSONObject){
		this.webInterface.setwebConfigData(d)
	}
	setWebviewDownload(fn:(url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => void ){
		this.webInterface.setWebviewDownload(fn)
	}
	setSchema(s:TmuiSchemaType[]){
		this.webInterface.setSchema(s)
	}
	setAllowLoadUrlWhites(s:string[]){
		this.webInterface.setAllowLoadUrlWhites(s)
	}
	setPostMessage(fn:(str:uniAppPostmessageType)=>void){
		this.webInterface.setPostMessage(fn)
	}
	
	// 设置用户代理字符串标识。
	setUserAgent(agent ?: string) {
		this.webInterface.setUserAgent(agent??'')
	}
	getUserAgent(fn:(arg:string)=>void){
		fn(this.webInterface.getUserAgent())
	}
	loadUrl(url : string) {
		this.webInterface.loadUrl(url)
	}
	evaJs(jsCode : string) {
		this.webInterface.evaJsAsync(jsCode)
	}
	destory(){
		this.webInterface.destory()
	}
	loadUrlmini(url:string){}


	
}