
export type XuiChineseToPinYinResult = {
  detail : string,
  zhuyin : string
}

export interface XuiChineseToPinYinFail extends IUniError {
  errCode : number
};

export type XuiChineseToPinYinOpts = {
	/** 待转换的字符串 */
  char : string
  success ?: (res : XuiChineseToPinYinResult) => void
  fail ?: (res : XuiChineseToPinYinFail) => void
  complete ?: (res : XuiChineseToPinYinResult|null) => void
}



