import { CameraView, camerareqPermissions, capture, start, close, pause, stop, open, setParamsObj } from "x_camrea_u"
import { buildView } from "./builder.ets"
import { BuilderNode, ComponentContent } from "@kit.ArkUI"
import { xCamreaUOpts } from '../interface.uts';
// 定义 buildButton 的参数类型
interface NativeXdblurOptions {
	blur : number
}
export class xCamreaU {
	$element : UniNativeViewElement;
	targetView : BuilderNode<[NativeXdblurOptions]> | null = null;
	// 初始化 buildButton 默认参数
	private params : NativeXdblurOptions = {
		blur: 30,
	}
	private paramsObj : UTSJSONObject = {
		capture: (val : string) => {
		},
		avrecorder: (val : string) => {
		},
		decoreder: (val : string[]) => {
		},
		flash: false,
		orientation: 'back',
		// scan,camera
		mode: 'camera'
	}
	constructor(element : UniNativeViewElement, opts : xCamreaUOpts) {
		// 绑定 wrapBuilder 函数
		this.targetView = element.bindHarmonyWrappedBuilder(wrapBuilder<[NativeXdblurOptions]>(buildView))
		this.$element = element
		// 绑定当前实例为自定义的controller，方便其他地方通过 element 获取使用
		this.$element.bindHarmonyController(this)
		// this.targetView.

	}
	setParamsObj(val : UTSJSONObject) {
		setParamsObj(val)
	}
	getIsOpeningCameraing() : boolean {
		// return this.camera!.getIsOpeningCameraing()
		return false
	}
	setCameraDir(dir : string) {
		// this.camera!.setCameraDir(dir)
	}
	setFlash(flash : boolean) {
		this.paramsObj.set('flash',flash)
		setParamsObj(this.paramsObj)
	}
	openCamrea() {
		open()
	}

	takePhoto(call : (path : string) => void) {
		this.paramsObj.set('capture',call)
		setParamsObj(this.paramsObj)
		capture()
	}
	start(call : (path : string) => void) {
		this.paramsObj.set('avrecorder',call)
		start()
	}
	pause() {
		pause()
	}

	stop() {
		stop()
	}

	/** 关闭相机 */
	close() {
		
		close()
	}
}

// 检查权限
export function checkPermissions() : Promise<boolean> {
	return camerareqPermissions(UTSHarmony.getCurrentWindow()!, UTSHarmony.getCurrentWindow()!.getUIContext()
}