import LinearLayout from 'android.widget.LinearLayout';
import WebView from 'android.webkit.WebView';


import Context from 'android.content.Context';
import ViewGroup from "android.view.ViewGroup";
import WebViewClient from 'android.webkit.WebViewClient';
import WebChromeClient from 'android.webkit.WebChromeClient';
import Bitmap from 'android.graphics.Bitmap';
import WebResourceRequest from "android.webkit.WebResourceRequest";
import WebResourceResponse from "android.webkit.WebResourceResponse";
import JavascriptInterface from "android.webkit.JavascriptInterface";
import { xWebviewUOpts, uniAppEvaJsTypeOnUpdate,TmuiSchemaType, uniAppPostmessageType } from '../interface';
import { jsCodeToBody, jsCodeToBodyEnd, jsCodeToBodyRepeat } from "../libs/evealJsJscore.uts"
import Toast from 'android.widget.Toast';
import ValueCallback from "android.webkit.ValueCallback";
import ConsoleMessage from "android.webkit.ConsoleMessage";
import AlertDialog from "androidx.appcompat.app.AlertDialog";
import DialogInterface from "android.content.DialogInterface";
import { WebAppInterface } from "./openAppToWebActions.uts";

import getCurrentPages from 'io.dcloud.uniapp.framework.getCurrentPages';
import onReady from 'io.dcloud.uniapp.framework.onReady';
import onUnload from 'io.dcloud.uniapp.framework.onUnload';
import onShow from 'io.dcloud.uniapp.framework.onShow';
import Message from 'android.os.Message';
import Uri from "android.net.Uri";
import KotlinArray from 'kotlin.Array';
import KotlinString from 'kotlin.String';
import File from 'java.io.File';
import DocumentsContract from "android.provider.DocumentsContract";
import MediaStore from "android.provider.MediaStore";
import Cursor from "android.database.Cursor";
import DownloadListener from "android.webkit.DownloadListener";
import PermissionRequest from "android.webkit.PermissionRequest";
import KeyEvent from "android.view.KeyEvent";
import Intent from "android.content.Intent";
import Activity from 'android.app.Activity';
import Color from 'android.graphics.Color';
import View from "android.view.View";
import BufferedReader from "java.io.BufferedReader";
import InputStreamReader from "java.io.InputStreamReader";
import FileInputStream from "java.io.FileInputStream";
import ByteArrayInputStream from "java.io.ByteArrayInputStream";
import FileNotFoundException from "java.io.FileNotFoundException";
import Fragment from "androidx.fragment.app.Fragment";

export class xWebviewU {
	private localHostUrlStr:string = "https://uniappx.tmui.design"
	private rootLocalPath:string = "https://uniappx.tmui.design"
	private isLocalMiniProram:boolean = false
	private $element : UniNativeViewElement;
	private targetView : LinearLayout | null = null;
	private config : xWebviewUOpts = {
		uniAppEvaJs: (url : string | null, methodName : string, callbackId ?: string, params ?: UTSJSONObject, onUpdate ?: uniAppEvaJsTypeOnUpdate) : Promise<UTSJSONObject|null> => Promise.resolve(null)
	}
	private webview : WebView | null = null;
	private webviewClient : WebViewClient | null = null;
	private webviewChromClient : WebChromeClient | null = null;
	private webviewDownloadListener : DownloadListener | null = null;
	private context : Context | null = null
	public webInterface : WebAppInterface | null = null
	public callbackOnUpdate = new Map<string, uniAppEvaJsTypeOnUpdate>()
	// 网页加载进度回调
	private webviewProgressChanged = (n : number) => { }
	private webviewDonwloadChanged = (url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => {}
	private filePathCallback : ValueCallback<KotlinArray<Uri>> | null = null;
	private schemas:TmuiSchemaType[] = [];
	private allowLoadUrlWhite:string[] = [];
	
	constructor(element : UniNativeViewElement) {
		this.$element = element;
		this.bindView();
	}
	destory(){
		this.webview = null;
		this.webviewClient = null
		this.webviewChromClient = null
		this.webviewDownloadListener = null
		this.webInterface = null
		this.filePathCallback = null
		this.callbackOnUpdate.clear()
	}
	private bindView() {
		this.setWebClient()
		this.context = this.$element.getAndroidActivity()!
		let parentView = new LinearLayout(this.context!);
		parentView.setFitsSystemWindows(false)
		parentView.setClipToPadding(false)
		this.webview = new WebView(this.context!)
		this.webview!.setFitsSystemWindows(false)
		this.webview!.setOverScrollMode(View.OVER_SCROLL_NEVER)
		this.webview!.setWebViewClient(this.webviewClient!)
		this.webview!.setWebChromeClient(this.webviewChromClient!)
		this.webview!.setDownloadListener(this.webviewDownloadListener!)
		this.webview.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT))
		this.webview.setBackgroundColor(Color.TRANSPARENT)
		parentView.addView(this.webview!)
		this.targetView = parentView
		this.$element.bindAndroidView(this.targetView!);
		const wsb = new WebAppInterface(this.context!, this.webview!, this.webviewChromClient!, this.webviewClient!, this.config)
		this.webInterface = wsb;
		
		
		
	}
	evaJs(callback : string) {
		let _this = this;
		UTSAndroid.getDispatcher("main").async(function (_) {
			_this.webview?.evaluateJavascript(callback, null)
		}, null)
	}
	private setWebClient() {
		let _this = this;
		let mLastUrl:string|null = ''
		class wbviewclient extends WebViewClient {
			constructor() {
				super()
			}
		
			override onPageStarted(view : WebView | null, url : string | null, favicon : Bitmap | null) {
				super.onPageStarted(view, url, favicon);
				class resultBack extends ValueCallback<string>{
					override onReceiveValue(value : string) {
					}
				}
				view?.evaluateJavascript(jsCodeToBody, null)
				// view?.evaluateJavascript(jsCodeToBody, new resultBack())
				_this.config?.onPageStart?.(url)
			}
			override onPageFinished(view : WebView | null, url : string | null) {
				if (url!=mLastUrl){
					view?.evaluateJavascript(jsCodeToBodyEnd, null)
					view?.evaluateJavascript(jsCodeToBodyRepeat, null)
					// _this.config?.onPageFinish?.(url)
				}
				
				mLastUrl = url
				super.onPageFinished(view, url);
			}

			// HTTP 错误时调用 (API 23+)
			override onReceivedHttpError(view : WebView | null, request : WebResourceRequest, errorResponse : WebResourceResponse) {
				const url = request?.getUrl().toString();
				_this.config?.onPageError?.(url)
				super.onReceivedHttpError(view, request, errorResponse);
			}
			// @ts-ignore
			override shouldOverrideKeyEvent(view : WebView | null, event: KeyEvent): Boolean {
				
			    if (event.keyCode == KeyEvent.KEYCODE_BACK && (view?.canGoBack()??false)) {
			        view?.goBack()
			        return true
			    }
			    return super.shouldOverrideKeyEvent(view, event)
			}
			// 根据文件扩展名返回 MIME 类型
			private getMimeType(filename:string ):string {
			    if (filename.endsWith(".js")) return "application/javascript";
			    if (filename.endsWith(".css")) return "text/css";
			    if (filename.endsWith(".html") || filename.endsWith(".htm")) return "text/html";
			    if (filename.endsWith(".png")) return "image/png";
			    if (filename.endsWith(".jpg") || filename.endsWith(".jpeg")) return "image/jpeg";
			    if (filename.endsWith(".gif")) return "image/gif";
			    if (filename.endsWith(".svg")) return "image/svg+xml";
			    if (filename.endsWith(".woff")) return "font/woff";
			    if (filename.endsWith(".woff2")) return "font/woff2";
			    if (filename.endsWith(".json")) return "application/json";
			    return "application/octet-stream"; // 默认
			}
			override shouldInterceptRequest(view : WebView | null, request : WebResourceRequest | null){
				if(!_this.isLocalMiniProram){
					return super.shouldInterceptRequest(view, request);
				}
				const uri = request!.getUrl()!;
				const url =uri.toString();
				
				const urlPath = uri.getPath()
				
				if(!url.startsWith(_this.localHostUrlStr)){
					return super.shouldInterceptRequest(view, request);
				}
				if(urlPath==null||urlPath==''||urlPath=="/") return null
				
				const relativePath = urlPath.startsWith("/") ? urlPath : urlPath+"/";
				const localFile = new File(_this.rootLocalPath, relativePath);
				
				if (!localFile.exists()) {
					const s = "Not Found"
					return new WebResourceResponse("text/plain", "UTF-8", new ByteArrayInputStream(s.toByteArray()));
				}
				
				 // 获取 MIME 类型
				const mimeType = this.getMimeType(localFile.getName());
				try {
					const fis:FileInputStream = new FileInputStream(localFile);
					return new WebResourceResponse(mimeType, "UTF-8", fis);
				} catch (e:FileNotFoundException ) {
					console.log("WebApp", "Failed to open file", e);
					return super.shouldInterceptRequest(view, request);
				}
						
				// const headers = request!.getRequestHeaders()! as Map<string,string>;
				return super.shouldInterceptRequest(view, request);
			}

			// @ts-ignore
			override shouldOverrideUrlLoading(view : WebView | null, req : WebResourceRequest | null) : boolean {
				// @ts-ignore
				const url = req?.url?.toString()??'';
				const disabled = _this.config?.allowLoadUrl?.(url) ?? true;
				let isAllowd = true;
				if(!disabled){
					return true;
				}
				if(_this.allowLoadUrlWhite.length>0){
					isAllowd = _this.allowLoadUrlWhite.some((el:string):boolean => el.indexOf(url)>-1)
				}
				
				if((url.startsWith('http')||url.startsWith('https'))&&!isAllowd){
					return true;
				}
				
				const isAppschem:boolean = _this.schemas.some((el:TmuiSchemaType):boolean => url.startsWith(el.schema));
				
				if(url.startsWith('tel:')){
					try {
						const intent = new Intent(Intent.ACTION_DIAL);
						intent.setData(Uri.parse(url)); // url 格式: tel:10086
						const activity = UTSAndroid.getUniActivity()! as Activity
						activity.startActivity(intent)
					} catch (e:Exception) {
						Toast.makeText(UTSAndroid.getAppContext()!, "无法拨打电话", Toast.LENGTH_SHORT).show();
					}
					return true;
				}else if(url.startsWith('mailto:')){
					try {
						const intent = new Intent(Intent.ACTION_SENDTO);
						intent.setData(Uri.parse(url));// url 格式: mailto:abc@163.com?subject=标题
						const activity = UTSAndroid.getUniActivity()! as Activity
						activity.startActivity(intent)
					} catch (e:Exception) {
						Toast.makeText(UTSAndroid.getAppContext()!, "找不到邮件APP", Toast.LENGTH_SHORT).show();
					}
					return true;
				}else if(url.startsWith("sms:") || url.startsWith("smsto:")){
					try {
						const intent = new Intent(Intent.ACTION_SENDTO);
						intent.setData(Uri.parse(url));// url 格式: sms:10086
						const activity = UTSAndroid.getUniActivity()! as Activity
						activity.startActivity(intent)
					} catch (e:Exception) {
						Toast.makeText(UTSAndroid.getAppContext()!, "无法发送短信", Toast.LENGTH_SHORT).show();
					}
					return true;
				}else if(isAppschem){
					try {
						const activity = UTSAndroid.getUniActivity()! as Activity
						const intent = new Intent(Intent.ACTION_VIEW, req?.url)
						if(activity.getPackageManager().resolveActivity(intent,0)!=null){
							activity.startActivity(intent)
						}else{
							let urlInstall = ''
							let urlHost = url.substring(0,url.indexOf('//')+2)
							for(let i=0;i<_this.schemas.length;i++){
								let item = _this.schemas[i]
								if(item.schema.startsWith(urlHost)){
									urlInstall = item.installUrl;
									break;
								}
							}
							if(urlInstall!=''){
								let intent = new Intent(Intent.ACTION_VIEW, Uri.parse(urlInstall))
								activity.startActivity(intent)
							}
						
						}
						
					} catch (e:Exception) {
						Toast.makeText(UTSAndroid.getAppContext()!, "打开失败", Toast.LENGTH_SHORT).show();
					}
					return true;
				}
				
				
				return false;
			}
		}
		// @ts-ignore
		this.webviewClient = new wbviewclient()
		class wbviewChromClient extends WebChromeClient {
			constructor() {
				super()
			}
			
			// @ts-ignore
			override onConsoleMessage(con : ConsoleMessage | null): boolean {
				console.log(`[Log][tmui4xJssdk][${new Date().toLocaleTimeString()}]:`, con?.message())
				return super.onConsoleMessage(con);
			}
			override onCreateWindow(view : WebView, isDialog : boolean, isUserGesture : boolean, resultMsg : Message) : boolean {
				super.onCreateWindow(view, isDialog, isUserGesture, resultMsg)
				return false
			}
			override onProgressChanged(view : WebView, newProgress : Int) {
				super.onProgressChanged(view, newProgress)
				_this.webviewProgressChanged(newProgress + 0)

			}
			override onPermissionRequest(request : PermissionRequest) : void {
				const resources = request.getResources()
				const resourceList = Array.fromNative(resources) as string[]
				const permissionNeed : string[] = []
				for (let i = 0; i < resourceList.length; i++) {
					const resource = resourceList[i]
					if (resource == PermissionRequest.RESOURCE_VIDEO_CAPTURE && !permissionNeed.includes("android.permission.CAMERA")) {
						permissionNeed.push("android.permission.CAMERA")
					} else if (resource == PermissionRequest.RESOURCE_AUDIO_CAPTURE && !permissionNeed.includes("android.permission.RECORD_AUDIO")) {
						permissionNeed.push("android.permission.RECORD_AUDIO")
					}
				}
				if (permissionNeed.length == 0) {
					request.grant(resources)
					return
				}
				const activity = UTSAndroid.getUniActivity()! as Activity
				UTSAndroid.requestSystemPermission(activity, permissionNeed, function (allRight : boolean, _ : string[]) {
					if (allRight) {
						request.grant(resources)
					} else {
						request.deny()
					}
				}, function (_ : boolean, _ : string[]) {
					request.deny()
				})
			}
			override onShowFileChooser(view : WebView, filePathCallback : ValueCallback<KotlinArray<Uri>>, fileChooserParams : WebChromeClient.FileChooserParams) : boolean {
				// super.onShowFileChooser(view, filePathCallback!, fileChooserParams)
				if (_this.filePathCallback != null) {
					_this.filePathCallback.onReceiveValue(null)
					_this.filePathCallback = null;
				}
				// 1. 获取H5标签中 accept 属性的值，例如 "image/*", "video/*", ".pdf"
				const acceptTypes : string[] = Array.fromNative(fileChooserParams.getAcceptTypes());
				// 2. 获取选择模式（单选/多选）
				const mode = fileChooserParams.getMode(); // OPEN_MODE_SINGLE 或 OPEN_MODE_MULTIPLE
				// 是否多选
				const isMult = mode == WebChromeClient.FileChooserParams.MODE_OPEN_MULTIPLE

				_this.filePathCallback = filePathCallback

				let isImage = false;
				let isVideo = false;
				let isAnyFile = false;
				// 是否仅相机取照片
				let isCapture = acceptTypes.length > 0 && fileChooserParams.isCaptureEnabled();
				if (acceptTypes.length == 0) {
					// 如果H5没写accept属性，默认通常处理为图片或所有文件
					isImage = true;
				} else {
					// 遍历所有类型进行判断
					for (let i = 0; i < acceptTypes.length; i++) {
						const acceptType = acceptTypes[i]
						if (acceptType.contains("image")) {
							isImage = true;
							break;
						} else if (acceptType.contains("video")) {
							isVideo = true;
							break;
						} else if (acceptType.equals("*/*")) {
							isAnyFile = true;
							break;
						}
					}


				}


				// 3. 根据判断结果，弹出不同的选择器
				if (isImage && !isVideo && !isAnyFile) {
					// @ts-ignore
					uni.chooseImage({
						albumMode: 'system',
						sizeType: ['compressed'],
						count: isMult ? 9 : 1,
						sourceType: isCapture ? ['camera'] : ['album', 'camera'],
						// @ts-ignore
						success(result : ChooseImageSuccess) {
							const files = result.tempFilePaths as string[]
							const uris = files.map((el : string) : Uri => {

								const file = new File(UTSAndroid.convert2AbsFullPath(el));
								return Uri.fromFile(file)
							})
							const fls = uris.toTypedArray();
							_this.filePathCallback?.onReceiveValue(fls)
							_this.filePathCallback = null;
						},
						fail(result) {
							_this.filePathCallback?.onReceiveValue(null)
							_this.filePathCallback = null;
						}
					})

					return true;
				} else if (isVideo) {
					// 包含视频，弹出视频选择器
					// @ts-ignore
					uni.chooseVideo({
						maxDuration: 60,
						sourceType: isCapture ? ['camera'] : ['album', 'camera'],
						// @ts-ignore
						success(result : ChooseVideoSuccess) {
							const file = result.tempFilePath as string
							const uris = [Uri.fromFile(new File(UTSAndroid.convert2AbsFullPath(file)))]
							const fls = uris.toTypedArray();
							_this.filePathCallback?.onReceiveValue(fls)
							_this.filePathCallback = null;
						},
						fail(result) {
							_this.filePathCallback?.onReceiveValue(null)
							_this.filePathCallback = null;
						}
					})
					return true;

				}

				_this.filePathCallback?.onReceiveValue(null)
				_this.filePathCallback = null;
				return true


			}

		}
		// @ts-ignore
		this.webviewChromClient = new wbviewChromClient()
		class webvewDownLoad extends DownloadListener{
			constructor(){
				super()
			}
			override onDownloadStart(url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:Long ){
				_this.webviewDonwloadChanged(url,userAgent,contentDisposition,mimeType,(contentLength+0))
				
			}
		}
		// @ts-ignore
		this.webviewDownloadListener = new webvewDownLoad()
		
	}
	@UTSJS.keepAlive
	@Suppress("DEPRECATION")
	setBaseConfig(opts : xWebviewUOpts) {
		this.config = opts;
		let browesr = this.webview!;
		this.webInterface?.setConfigs(opts)
		const cfg = browesr.getSettings()
		cfg.setJavaScriptEnabled(true)
		cfg.setDomStorageEnabled(true)
		cfg.setDatabaseEnabled(true)
		// cfg.setAllowFileAccessFromFileURLs(true)
		// cfg.setAllowUniversalAccessFromFileURLs(true)
		//允许访问文件。
		// cfg.setAllowFileAccess(true)
		cfg.setAllowContentAccess(true)
		browesr.addJavascriptInterface(this.webInterface!, 'tmuiApp')
		
		
		
		if ((this.config?.url ?? '') != '') {
			this.isLocalMiniProram = false;
			this.loadUrl(this.config!.url!)
		}
	}
	// 设置用户代理字符串标识。
	setUserAgent(agent ?: string) {
		let browesr = this.webview!;
		const agentUser = agent ?? ' Tmui4xApp/1.1.20'
		const cfg = browesr.getSettings()
		const selftAgent = cfg.getUserAgentString()
		cfg.setUserAgentString(selftAgent + agentUser)
	}
	getUserAgent(fn:(ag:string)=>void){
		let browesr = this.webview!;
		const cfg = browesr.getSettings()
		const selftAgent = cfg.getUserAgentString()
		fn(selftAgent)
	}
	loadUrl(url : string) {
		this.isLocalMiniProram = false;
		let browesr = this.webview!;
		browesr.loadUrl(url)
		
	}
	private readFileToString(file:File):string{
	    const sb:StringBuilder = new StringBuilder();
	   let br = new BufferedReader(new InputStreamReader(new FileInputStream(file)))
	   let line = br.readLine();
	   while ( line != null) {
	       sb.append(line).append("\n");
	   	(line = br.readLine())
	   }
	    return sb.toString();
	}
	loadUrlmini(url:string){
		this.isLocalMiniProram = true;
		// 是否启用离线模式小程序模式。
		const paths = UTSAndroid.convert2AbsFullPath(url)
		const ac = UTSAndroid.getUniActivity()! as Activity
		const purl:File =new File(paths)
		this.rootLocalPath = paths.substring(0, paths.lastIndexOf("/"));
		// ac.grantUriPermission(WebView.getCurrentWebViewPackage()?.packageName,UTSAndroid.getFileProviderUri(new File(url)),Intent.FLAG_GRANT_READ_URI_PERMISSION)
		let browesr = this.webview!;
		const baseUrl = this.localHostUrlStr;
		const htmlContent = this.readFileToString(purl)
		browesr.loadDataWithBaseURL(baseUrl,htmlContent,"text/html", "UTF-8", null)
	}
	@UTSJS.keepAlive
	setWebviewLoadUrlProgress(callback : (progress : number) => void) {
		this.webviewProgressChanged = callback
	}
	@UTSJS.keepAlive
	setWebviewDownload(callback:(url:string , userAgent:string , contentDisposition:string , mimeType:string , contentLength:number) => void ){
		this.webviewDonwloadChanged = callback
	}
	@UTSJS.keepAlive
	setPostMessage(fn:(arg:uniAppPostmessageType)=>void){
		this.webInterface?.setPostMessageFn((event:uniAppPostmessageType)=>{
			fn(event)
		})
	}
	
	setwebConfigData(d:UTSJSONObject){
		this.webInterface?.setwebConfigData(d)
	}
	setSchema(s:TmuiSchemaType[]){
		this.schemas = s;
	}
	setAllowLoadUrlWhites(s:string[]){
		this.allowLoadUrlWhite = s;
	}

	
}

