import LinearLayout from 'android.widget.LinearLayout';
import WebView from 'android.webkit.WebView';
import Context from 'android.content.Context';
import ViewGroup from "android.view.ViewGroup";
import WebViewClient from 'android.webkit.WebViewClient';
import WebChromeClient from 'android.webkit.WebChromeClient';

import JavascriptInterface from "android.webkit.JavascriptInterface";
import { xWebviewUOpts,uniAppEvaJsTypeOnUpdate,xWebviewUCallMethodType, uniAppEvaJsTypeCallBackFun, uniAppPostmessageType,uniAppDownLoadMessageType } from '../interface';
import Toast from 'android.widget.Toast';
import ValueCallback from "android.webkit.ValueCallback";
import Build from "android.os.Build";

// import getCurrentPages from 'io.dcloud.uniapp.framework.getCurrentPages';
// import onReady from 'io.dcloud.uniapp.framework.onReady';
// import onUnload from 'io.dcloud.uniapp.framework.onUnload';
// import onShow from 'io.dcloud.uniapp.framework.onShow';
import Intent from 'android.content.Intent';
import Uri from 'android.net.Uri';
import Activity from 'android.app.Activity';

export class WebAppInterface {
	//--- 防止摇树被删除。开始---
	private _uniAppDownLoadMessageType__:uniAppDownLoadMessageType|null = null
	private _xWebviewUCallMethodType__:xWebviewUCallMethodType|null = null;
	//---防止摇树被删除。结束---
	
	ctx : Context;
	webview : WebView;
	webChormClient : WebChromeClient;
	webClient : WebViewClient;
	config : xWebviewUOpts
	private webConfig:UTSJSONObject = {}
	private postMessageCallback = (arg:uniAppPostmessageType)=>{}
	constructor(ctx : Context, webview : WebView, webChormClient : WebChromeClient, webClient : WebViewClient, config : xWebviewUOpts) {
		this.ctx = ctx;
		this.webview = webview;
		this.webChormClient = webChormClient;
		this.webClient = webClient;
		this.config = config;
	}
	
	setConfigs(cfg:xWebviewUOpts){
		this.config = cfg;
		
	}
	
	
	
	/** 刷新页面 */
	// @ts-ignore
	@JavascriptInterface
	public refresh(){
		UTSAndroid.getDispatcher("main").async(function (_) {
			this.webview.reload()
		}, null)
	}
	
	/** 回退页面 */
	// @ts-ignore
	@JavascriptInterface
	public navback(){
		UTSAndroid.getDispatcher("main").async(function (_) {
			this.webview.goBack()
		}, null)
	}
	
	/** 前进页面 */
	// @ts-ignore
	@JavascriptInterface
	public forward(){
		UTSAndroid.getDispatcher("main").async(function (_) {
			this.webview.goForward()
		}, null)
	}
	
	public evaJs(jscode:string):Promise<string|null>{
		const _this = this;
		return new Promise((res)=>{
			UTSAndroid.getDispatcher("main").async(function (_) {
				class resultBack extends ValueCallback<string>{
					override onReceiveValue(value:string|null) {
						res(value)
					}
				}
				
				_this.webview.evaluateJavascript(jscode,new resultBack())
			}, null)
		})
	}
	public evaJsAsync(jscode:string){
		const _this = this;
		UTSAndroid.getDispatcher("main").async(function (_) {
			_this.webview.evaluateJavascript(jscode,null)
		}, null)
	}
	performActionWithCallback(callback : string) {
		let _this = this;
		
		UTSAndroid.getDispatcher("main").async(function (_) {
			_this.webview.evaluateJavascript(callback, null)
		}, null)
	}
	@Suppress("DEPRECATION")
	methodFun(methodName:string,callbackId?:string,params?:UTSJSONObject):Promise<UTSJSONObject|null>{
		if(callbackId==null) return Promise.resolve(null);
		if(methodName == 'app_getWebviewInfo'){
			const result = WebView.getCurrentWebViewPackage();
			if(result == null) {
				return Promise.resolve({
					callbackId:callbackId!,
					success:false,
					errorMessage:null,
					data:null
				} as UTSJSONObject);
			}
			const d = {
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:{
					packageName:result.packageName,
					versionName:result.versionName,
					versionCode:result.versionCode,
					apiLevel: Build.VERSION.SDK_INT,
					env:"uniapp-x android"
				}
			} as UTSJSONObject
			return Promise.resolve(d);
		}else if(methodName == 'app_openUrl'){
			let intent = new Intent(Intent.ACTION_VIEW, Uri.parse(params?.getString('url')??''))
			let ac = UTSAndroid.getUniActivity() as Activity
			ac.startActivity(intent)
			return Promise.resolve({
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:null
			} as UTSJSONObject);
		}else if(methodName == 'app_getUserAgent'){
			return Promise.resolve({
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:this.getUserAgent()
			} as UTSJSONObject);
		}else if(methodName == 'app_getConfig'){
			console.log(this.webConfig)
			return Promise.resolve({
				callbackId:callbackId!,
				success:true,
				errorMessage:null,
				data:this.webConfig
			} as UTSJSONObject);
		}
		return Promise.resolve(null);
	}

	/**
	 * 消息提示（私有函数）
	 * @param message 内容
	 */
	// @ts-ignore
	@JavascriptInterface
	handleWebMessage(arg?:string){
		let _this = this;
		if(arg == null||arg=='') return;
		UTSAndroid.getDispatcher("main").async(function (_) {
			try {
				const message = JSON.parseObject(arg)
				if(message == null) return;
				const callbackId = message.getString('callbackId')??null;
				const methodName = message.getString('methodName')??null;
				const params = message.getJSON('params')??null;
				if(methodName == null) return;
				
				//分发到本插件宿主环境执行
				if(methodName.startsWith('app_')){
					_this.methodFun(methodName,callbackId,params)
					.then((result:UTSJSONObject|null)=>{
				
						if(callbackId==null) return;
						_this.performActionWithCallback(`__handleTmuiResponse('${result==null?JSON.stringify({}):JSON.stringify(result!)}')`)
					})
				// 系统分发到uniapp环境执行	
				}else{
					const onUpdate:uniAppEvaJsTypeOnUpdate = (result:any|null) =>{
						_this.performActionWithCallback(`__handleTmuiResponse('${result==null?JSON.stringify({}):JSON.stringify(result!)}')`)
					}
					const onCallbackFun:uniAppEvaJsTypeCallBackFun = (result:UTSJSONObject|null) =>{
						if(callbackId==null) return;
						_this.performActionWithCallback(`__handleTmuiResponse('${JSON.stringify(result==null?({}):result!)}')`)
					}
					_this.config?.uniAppEvaJsIos?.(_this.webview.getUrl(),methodName!,callbackId,params,onUpdate,onCallbackFun)
					
					// _this.config.uniAppEvaJsIos(_this.webview.getUrl(),methodName,callbackId,params,(result?:any|null)=>{
					// 	_this.performActionWithCallback(`__handleTmuiResponse('${result==null?JSON.stringify({}):JSON.stringify(result!)}')`)
					// })
					// .then((result:UTSJSONObject)=>{
					// 	if(callbackId==null) return;
					// 	_this.performActionWithCallback(`__handleTmuiResponse('${JSON.stringify(result==null?({}):result!)}')`)
					// })
				}
				
			} catch (error) {
				console.error('TMUIWEBVIEW ERROR',error)
				const message = JSON.parseObject(arg)
				if(message == null) return;
				const callbackId = message.getString('callbackId')??null;
				const methodName = message.getString('methodName')??null;
				if(methodName == null) return;
				const result = {
					callbackId:callbackId!,
					success:true,
					errorMessage:'TMUIWEBVIEW ERROR',
					data:null
				} as UTSJSONObject
				_this.performActionWithCallback(`__handleTmuiResponse('${JSON.stringify(result)}')`)
			}
			
		}, null)
	}
	
	/**
	 * 消息提示（私有函数）
	 * @param message 内容
	 */
	// @ts-ignore
	@JavascriptInterface
	public toast(message : string) {
		Toast.makeText(this.ctx, message, Toast.LENGTH_SHORT).show()
	}
	
	/**
	 * body高度变化(私有函数)
	 */
	// @ts-ignore
	@JavascriptInterface
	public contentHeightChange(arg:string){
		this.config?.uniActions?.('contentHeightChange',parseFloat(arg))
	}
	// @ts-ignore
	@JavascriptInterface
	public pageOnloaded(arg:string){
		this.config?.onPageFinish?.(arg)
	}
	
	
	/**
	 * 执行宿主应用
	 */
	// @ts-ignore
	@JavascriptInterface
	public loadUrl(url:string){
		this.webview.loadUrl(url)
	}
	// @ts-ignore
	@JavascriptInterface
	clearCache(){
		UTSAndroid.getDispatcher("main").async(function (_) {
			this.webview.clearCache(true)
			this.webview.reload()
		}, null)
	}
	
	/**
	 * 执行宿主自定函数事件
	 */
	// @ts-ignore
	@JavascriptInterface
	public postMessage(arg?:string){
		let msg = arg??''
		UTSAndroid.getDispatcher("main").async(function (_) {
			this.postMessageCallback({detail:msg} as uniAppPostmessageType)
		})
	}
	setPostMessageFn(fn:(arg:uniAppPostmessageType)=>void){
		this.postMessageCallback = fn;
	}
	/**
	 * 设置用户代理字符串标识
	 */
	// @ts-ignore
	setUserAgent(agent?:string){
		const browesr = this.webview;
		const agentUser = agent??""
		const cfg = browesr.getSettings()
		const selftAgent = cfg.getUserAgentString()
		cfg.setUserAgentString(selftAgent + agentUser)
	}
	
	getUserAgent():string{
		const browesr = this.webview;
		const cfg = browesr.getSettings()
		const selftAgent = cfg.getUserAgentString()
		return selftAgent
	}
	
	setwebConfigData(d:UTSJSONObject){
		this.webConfig = d;
	}
	
	/**
	 * 设置用户代理字符串标识
	 */
	// @ts-ignore
	@JavascriptInterface
	getConfig():string{
		return JSON.stringify(this.webConfig);
	}

}

