import { XTOAST_TYPE, XTIPS_TYPE_PRIVATE } from "../interface.uts"
import { defaultConfig, configCover } from "../libs/config.uts"
import { hexToRgb } from "../libs/color.uts"
import { xshowtoasts,xhidetoasts } from "x_toast_s";



export const hideToast = () => {
	xhidetoasts(UTSHarmony.getCurrentWindow()!.getUIContext())
}
export function showToast(opts : XTOAST_TYPE|null) {
	let config = configCover(opts==null ? ({} as XTOAST_TYPE) : (opts!))
	xshowtoasts(UTSHarmony.getCurrentWindow()!.getUIContext(),config)
}