
export type XScreenshotFormat = 'png' | 'jpg'

export type XScreenshotResult = {
	/** 截图保存后的本地文件路径 */
	path : string
}

export interface XScreenshotFail extends IUniError {
	errCode : number
}

export type XScreenshotOpts = {
	/** 要截图的目标元素 */
	ele ?: UniElement | null
	/** 保存格式，默认 png */
	format ?: XScreenshotFormat
	success ?: (res : XScreenshotResult) => void
	fail ?: (res : XScreenshotFail) => void
	complete ?: (res : XScreenshotResult | null) => void
}

