/* 此规范为 uni 规范，可以按照自己的需要选择是否实现 */
import { XScreenshotFail } from "./interface.uts"

export const XuiErrors : Map<number, string> = new Map([
	[1001, '截图失败，无法保存图片'],
	[1002, '未知错误，请查阅日志了解详情'],
	[1003, '元素为空或无法获取原生 View'],
	[1004, '目标 View 宽高为 0'],
	[1005, '当前平台不支持截图'],
	[1006, '系统版本过低，不支持截图'],
	[1007, '参数 format 仅支持 png、jpg'],
]);

export class XScreenshotImpl extends UniError implements XScreenshotFail {
	constructor(errCode : number) {
		super();
		this.errSubject = "x-screenshot-s";
		this.errCode = errCode;
		this.errMsg = XuiErrors.get(errCode) ?? "";
	}
}
