// 页面加载前注入
export const jsCodeToBody = `(function(global){
	if(global.jsCodeToBody === true) return;
	global.jsCodeToBody = true;
	class TmuiAppEmiterClass{
		constructor() {
			this.events = new Map();
			this.emits = new Map();
		}
		emit(event, data) {
			this.emits.set(event,data)
			this.runDipatch(event)
		}
		runDipatch(event) {
			
			if(this.emits.has(event)) {
				var data = this.emits.get(event);
				var events = this.events.get(event)||[];
				events.forEach(function(el) {
					if (!el.status||el.repate) {
						el.callback(data);
						el.status = true;
					}
				});
				
			}
		}
		on(event, callback,repate) {
			var events = this.events.has(event)?this.events.get(event):[]
			var emitfun = {
				status:false,
				repate:repate||false,
				callback:callback
			}
			events.push(emitfun)
			this.events.set(event,events)
			this.runDipatch(event)

		}
	}
	window.tmuiAppEmiter = new TmuiAppEmiterClass()
	
})(window)`

// 页面加载后注入
export const jsCodeToBodyEnd = `(function(){
	if(window.jsCodeToBodyEnd === true) return;
	window.jsCodeToBodyEnd = true;
	function obserBodyHeightChange(){
		var targetDiv = document.body
		function getBodyHeight() {
			var height = targetDiv.scrollHeight
			tmuiApp.contentHeightChange(height+'')
		}
		var observer = new MutationObserver(function(mutations) {
			mutations.forEach(function(mutation) {
				if (mutation.type === 'attributes' && mutation.attributeName === 'style') {
					getBodyHeight()
				}
			});
		});
		// 配置观察选项:
		var config = {
			attributes: true, attributeFilter: ['style']
		};
		observer.observe(document.body, config);
		
		
	}
	obserBodyHeightChange()
	window.onload = function(){
		tmuiApp.pageOnloaded(location.href)
	}
})()`

//任意页面加载会重复注入（主要是pwa页面应用。）
export const jsCodeToBodyRepeat = `(function(){
// window.tmuiJssdk.setPageStyle({navigationBarTitleText:document.title})
})()
`

