import { WKUserScript, WKUserScriptInjectionTime } from 'WebKit';
import { NSObject } from 'ObjectiveC';
import { NSString } from 'Foundation';
// 注入的console.log
const ovriConsole = `(function() {
    if (window.consoleHooked) return;
    window.consoleHooked = true;

    const sendLog = function(level, args) {
        // 将 arguments 转为普通数组
        const serializableArgs = Array.prototype.slice.call(args).map(arg => {
            if (typeof arg === 'object') {
                try {
                    return JSON.stringify(arg);
                } catch (e) {
                    return '[Circular]' + (arg?.toString ? arg.toString() : 'Object');
                }
            }
            return String(arg);
        });

        window.webkit.messageHandlers.tmuiAppLog.postMessage({
            level: level,
            args: serializableArgs
        });
    };

    // 重写 console 方法
    const levels = ['log', 'info', 'warn', 'error', 'debug'];
    levels.forEach(level => {
        const original = console[level];
        console[level] = function(...args) {
            sendLog(level, args);
            // 可选：是否保留原始输出（在 Safari Web Inspector 中仍可见）
            // original.apply(console, args);
        };
    });
})();`

export const addConsoloeJs = new WKUserScript(
	source = ovriConsole,
	injectionTime = WKUserScriptInjectionTime.atDocumentStart,
	forMainFrameOnly = false
)


export class ConsoleLogHandler implements WKScriptMessageHandler<NSObject>{
	userContentController(userContentController : WKUserContentController, @argumentLabel("didReceive") message : WKScriptMessage) {
		const messageName = message.name;
		if (messageName != 'tmuiAppLog' || message.body == null) return;
		const body = message.body as Map<string, any>
		const action = body.get('level') as NSString | null;
		const data = body.get('args')
		const date = new Date();
		const h = date.getHours();
		const m = date.getHours();
		const s = date.getHours();
		const dateStr = `${h}:${m}:${s}`
		const level = action?.uppercased ?? 'Log';
		console.log(`[${level}][tmui4xJssdk][${dateStr}]:`, Array.isArray(data) ? (data as Array<string>).join(',') : data)
	}
}

// 注入一个tmuiAPP对象与安卓对齐。
export const overMessageActions = (arg:string,styleVar:string):string=>{
	return `
	
(function() {
    if (window.tmuiAppHooked) return;
    window.tmuiAppHooked = true;
	window.styleRootStyleByTmuiNativeMethodIos = function() {
		let val = JSON.parse(${styleVar}) || {};
		for (let key in val) {
			if (val.hasOwnProperty(key)) {
				if (key == '--tmui-dark') {
					document.documentElement.setAttribute('tmui-dark', val[key]);
				} else {
					document.documentElement.style.setProperty(key, val[key]);
				}
	
			}
		}
	};
	
	window.tmuiAppTheme = ${arg};
    window.tmuiApp = {
		refresh(){
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'refresh',
			    data: ''
			});
		},
		navback(){
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'navback',
			    data: ''
			});
		},
		forward(){
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'forward',
			    data: ''
			});
		},
		clearCache(){
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'clearCache',
			    data: ''
			});
		},
		toast(str){
			if(str==''||typeof str !=='string') return;
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'toast',
			    data: ''
			});
		},
		handleWebMessage(str){
			if(str==''||typeof str !=='string') return;
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'postMessage',
			    data: str
			});
		},
		postMessage(str){
			if(str==''||typeof str !=='string') return;
			window.webkit.messageHandlers.tmuiApp.postMessage({
			    action: 'postMessageCustom',
			    data: str
			});
		}
	}
	window.addEventListener('load', function(){
	  window.webkit.messageHandlers.tmuiApp.postMessage({
	      action: 'tmuiAppPageLoad',
	      data: ''
	  });
	});
	class TmuiAppEmiterClass{
		
		constructor() {
			this.events = new Map();
			this.emits = new Map();
		}
		emit(event, data) {
			this.emits.set(event,data)
			this.runDipatch(event)
		}
		runDipatch(event) {
			
			if(this.emits.has(event)) {
				var data = this.emits.get(event);
				var events = this.events.get(event)||[];
				events.forEach(function(el) {
					if (!el.status||el.repate) {
						el.callback(data);
						el.status = true;
					}
				});
				
			}
		}
		on(event, callback,repate) {
			var events = this.events.has(event)?this.events.get(event):[]
			var emitfun = {
				status:false,
				repate:repate||false,
				callback:callback
			}
			events.push(emitfun)
			this.events.set(event,events)
			this.runDipatch(event)
	
		}
	}
	window.tmuiAppEmiter = new TmuiAppEmiterClass()
})();`
}


// 模拟加载进度条。与安卓对齐。

const ovriAddLoadProgressJs = `(function() {
    if (window.LoadProgressJsHooked) return;
    window.LoadProgressJsHooked = true;
    window.addEventListener('load', function(){
	  styleRootStyleByTmuiNativeMethodIos()
	  window.webkit.messageHandlers.tmuiAppPageLoad.postMessage({
	      action: 'tmuiAppPageLoad',
	      data: ''
	  });
	});
})();`
export const addAddLoadProgressJs= new WKUserScript(
	source = ovriAddLoadProgressJs,
	injectionTime = WKUserScriptInjectionTime.atDocumentStart,
	forMainFrameOnly = false
)