import { BuilderNode, ComponentContent } from "@kit.ArkUI"
import { image } from '@kit.ImageKit';
import * from '@ohos.multimedia.image';
import { buildXdBlurView, buildXdParentBlurView } from "./builder.ets"
import { xBlurOpts } from "../interface.uts"
// 定义 buildButton 的参数类型
interface NativeXdblurOptions {
	blur : number,
	bgColor : string
}
export class XblurU {
	$element : UniNativeViewElement;
	targetView : BuilderNode<[NativeXdblurOptions]> | null = null;
	config : xBlurOpts;
	private params : NativeXdblurOptions = {
		blur: 20,
		bgColor: 'rgba(255,255,255,0.9)'
	}
	constructor(opts : xBlurOpts) {
		this.config = opts
		this.params.bgColor = opts.bgColor
		this.params.blur = opts.blur
		this.$element = opts.ele as UniNativeViewElement;
		// 绑定 wrapBuilder 函数
		this.targetView = this.$element.bindHarmonyWrappedBuilder(wrapBuilder<[NativeXdblurOptions]>(buildXdBlurView), this.params)
		// 绑定当前实例为自定义的controller，方便其他地方通过 element 获取使用
		this.$element.bindHarmonyController(this)
	}

	updateEffect(bgColor : string, blur : number) {
		this.config.bgColor = bgColor
		this.config.blur = blur
		this.params.bgColor = bgColor
		this.params.blur = blur
		this.targetView?.update(this.params)
	}

}